config/routes.rb
Rails.application.routes.draw do
  resources :slides

  resources :category_products

  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :who_bought, on: :member
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :image_attachments

  resources :line_item_attributes

  resources :product_attributes

  resources :orders
  resources :orders do
    member do
      post 'shipped'
    end
  end

  resources :line_items
  resources :carts
  get 'payment', to: 'store#payment', as: 'payment'
  get 'contacts', to: 'store#contacts', as: 'contacts'
  get 'about', to: 'store#about', as: 'about'
  get 'store/index'
  get 'store/search', to: 'store#search', as: 'store_search'
  get 'store/:id', to: 'store#show', as: 'store_show'
  resources :products

  root to: 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product, params)
		quantity = params[:quantity].to_i || 1

		current_item = line_items.where(product_id: product.id).map do |current|
			product_attributes = params.reject { |key, value| product.product_attributes.find_by(title: key, id: value).nil? }.map{|key, value| value.to_i}
			if current.line_item_attribute.pluck(:product_attribute_id).uniq.sort == product_attributes.uniq.sort
				current.quantity += quantity
				current
			else
				nil
			end
		end

		unless current_item.nil? || current_item.empty?
			current_item = current_item.compact.first
		end

		if current_item.nil? || current_item == []
			current_item = line_items.build(product_id: product.id, quantity: quantity)
			params.each do |key, value|
		      	attribute_attribute = product.product_attributes.find_by(title: key, id: value)
		      	unless attribute_attribute.nil?
		        	current_item.line_item_attribute.build(product_attribute_id: attribute_attribute.id)
		      	end
	    	end
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :category_products, dependent: :destroy
	has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/image_attachment.rb
class ImageAttachment < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  has_many :line_item_attribute

  def price
  	product.price + line_item_attribute.to_a.sum {|n| n.product_attribute.price.to_i}
  end

  def total_price
  	price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :email, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#	validates :status, inclusion: {in: valid_status}, presence: true
	has_many :line_items, dependent: :destroy

	STATUS = {
		ordered: 'Заказ размещен',
		changed: 'Были внесены изменения в заказ',
		shipped: 'Заказ отправлен',
		archived: 'В архиве'
	}

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
			self.status = STATUS[:ordered]
		end
	end

	def self.status
		STATUS
	end

	def change_status(new_status)
		self.status = STATUS[new_status]
	end

	def self.valid_status
		STATUS.keys
	end
end

app/models/product.rb
require 'babosa'

class Product < ActiveRecord::Base
	searchkick
	extend FriendlyId
	friendly_id :slug_candidates, use: [:slugged, :finders]
	validates :title, :price, presence: true
	has_many :line_items
	has_many :category_products
	has_many :categories, through: :category_products
	has_many :product_attributes
	has_many :image_attachments
	accepts_nested_attributes_for :image_attachments
	has_many :orders, through: :line_items
  	attr_accessor :quantity

	before_destroy :ensure_not_referenced_by_any_line_item

	def quantity
	  @quantity || 1
	end

	def quantity=(value)
	  @quantity = value
	end

	def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  	end

	def normalize_friendly_id(text)
		text.to_s.to_slug.normalize(transliterations: :russian).to_s
	end

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end
end

app/models/product_attribute.rb
class ProductAttribute < ActiveRecord::Base
  validates :title, :value, :product_id, presence: true
  belongs_to :product, dependent: :destroy
end

app/models/slide.rb
class Slide < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  validates :name, presence: true, uniqueness: true
  has_secure_password

  private
  	def ensure_an_admin_remains
  		if User.count.zero?
  			raise "Последний пользователь не может быть удален."
  		end
  	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h2 class="header">Панель управления</h2>

Имеется <%= pluralize @total_orders, "orders" %>

<br><br>

<h3 class="header">Доступ к ресурсам</h3>

<div class="collection">
	<%= link_to 'Заказы', orders_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Продукты', products_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Категории', categories_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Связь продуктов и категорий', category_products_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Администраторы', users_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Товарные позиции', line_items_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Корзины', carts_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Изображения', image_attachments_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Атрибуты продуктов', product_attributes_path, class: "waves-effect waves-light collection-item" %>
	<%= link_to 'Слайдер', slides_path, class: "waves-effect waves-light collection-item" %>
</div>

app/views/order_notifier/ordered.html.erb
<h3>
	Получен заказ от клиента <%= @order.name.to_s %>
</h3>

<table>
	<thead>
    	<tr>
    		<th></th>
        	<th data-field="title">Товарная позиция</th>
        	<th data-field="quantity">Количество</th>
        	<th data-field="price">Цена</th>
    	</tr>
    </thead>
	<%= render @order.line_items -%>
</table>

app/views/order_notifier/received.html.erb
<h3>
	Уважаемый(ая) <%= @order.name || 'клиент' %>
</h3>

<p>
	Администрация интернет магазина "Спорт-юниор" благодарит Вас за недавний заказ.<br>
	Вы заказали следующий товар:
</p>

<table>
	<thead>
    	<tr>
    		<th></th>
        	<th data-field="title">Товарная позиция</th>
        	<th data-field="quantity">Количество</th>
        	<th data-field="price">Цена</th>
    	</tr>
    </thead>
	<%= render @order.line_items -%>
</table>

Когда Ваш заказ будет отправлен, мы вышлем Вам по электронной почте отдельное сообщение.

app/views/order_notifier/received.text.erb
Уважаемый(ая) <%= @order.name || 'клиент' %>

Администрация интернет магазина "Спорт-юниор" благодарит Вас за недавний заказ.
Вы заказали следующий товар:

<%= render @order.line_items -%>

Когда Ваш заказ будет отправлен, мы пошлем Вам по электронной почте отдельное сообщение.

app/views/order_notifier/shipped.html.erb
<h3>
	Заказ из интернет магазина "Спорт-юниор" отправлен
</h3>

<p>
	Это сообщение уведомляет Вас, что мы отправили Ваш недавний заказ:
</p>

<table>
	<thead>
    	<tr>
    		<th></th>
        	<th data-field="title">Товарная позиция</th>
        	<th data-field="quantity">Количество</th>
        	<th data-field="price">Цена</th>
    	</tr>
    </thead>
	<%= render @order.line_items -%>
</table>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb