config/routes.rb
Rails.application.routes.draw do
  resources :slides

  resources :category_products

  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :who_bought, on: :member
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :image_attachments

  resources :line_item_attributes

  resources :product_attributes

  resources :orders
  resources :orders do
    member do
      post 'shipped'
    end
  end

  resources :line_items
  resources :carts
  get 'payment', to: 'store#payment', as: 'payment'
  get 'contacts', to: 'store#contacts', as: 'contacts'
  get 'about', to: 'store#about', as: 'about'
  get 'store/index'
  get 'store/search', to: 'store#search', as: 'store_search'
  get 'store/:id', to: 'store#show', as: 'store_show'
  resources :products

  root to: 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product, params)
		quantity = params[:quantity].to_i || 1

		current_item = line_items.where(product_id: product.id).map do |current|
			product_attributes = params.reject { |key, value| product.product_attributes.find_by(title: key, id: value).nil? }.map{|key, value| value.to_i}
			if current.line_item_attribute.pluck(:product_attribute_id).uniq.sort == product_attributes.uniq.sort
				current.quantity += quantity
				current
			else
				nil
			end
		end

		unless current_item.nil? || current_item.empty?
			current_item = current_item.compact.first
		end

		if current_item.nil? || current_item == []
			current_item = line_items.build(product_id: product.id, quantity: quantity)
			params.each do |key, value|
		      	attribute_attribute = product.product_attributes.find_by(title: key, id: value)
		      	unless attribute_attribute.nil?
		        	current_item.line_item_attribute.build(product_attribute_id: attribute_attribute.id)
		      	end
	    	end
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :category_products, dependent: :destroy
	has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/image_attachment.rb
class ImageAttachment < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  has_many :line_item_attribute

  def price
  	product.price + line_item_attribute.to_a.sum {|n| n.product_attribute.price.to_i}
  end

  def total_price
  	price * quantity
  end
end

app/models/line_item_attribute.rb
class LineItemAttribute < ActiveRecord::Base
  belongs_to :product_attribute
  belongs_to :line_item
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :email, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#	validates :status, inclusion: {in: valid_status}, presence: true
	has_many :line_items, dependent: :destroy

	STATUS = {
		ordered: 'Заказ размещен',
		changed: 'Были внесены изменения в заказ',
		shipped: 'Заказ отправлен',
		archived: 'В архиве'
	}

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
			self.status = STATUS[:ordered]
		end
	end

	def self.status
		STATUS
	end

	def change_status(new_status)
		self.status = STATUS[new_status]
	end

	def self.valid_status
		STATUS.keys
	end
end

app/models/product.rb
require 'babosa'

class Product < ActiveRecord::Base
	searchkick
	extend FriendlyId
	friendly_id :slug_candidates, use: [:slugged, :finders]
	validates :title, :price, presence: true
	has_many :line_items
	has_many :category_products
	has_many :categories, through: :category_products
	has_many :product_attributes
	has_many :image_attachments
	accepts_nested_attributes_for :image_attachments
	has_many :orders, through: :line_items
  	attr_accessor :quantity

	before_destroy :ensure_not_referenced_by_any_line_item

	def quantity
	  @quantity || 1
	end

	def quantity=(value)
	  @quantity = value
	end

	def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  	end

	def normalize_friendly_id(text)
		text.to_s.to_slug.normalize(transliterations: :russian).to_s
	end

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end
end

app/models/product_attribute.rb
class ProductAttribute < ActiveRecord::Base
  validates :title, :value, :product_id, presence: true
  belongs_to :product, dependent: :destroy
end

app/models/slide.rb
class Slide < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  validates :name, presence: true, uniqueness: true
  has_secure_password

  private
  	def ensure_an_admin_remains
  		if User.count.zero?
  			raise "Последний пользователь не может быть удален."
  		end
  	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:show, :create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  include CategoriesAvailable
  before_action :categories

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Cart was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_badge.html.erb
<% unless @cart.nil? || @cart.line_items.count.zero? %>
	<span class="new badge">
		<%= @cart.line_items.count %>
	</span>
<% end %>

app/views/carts/_cart.html.erb
<div id="cart">
	<h2 class="header">Корзина</h2>
	<br>
	<table class="bordered z-depth-1">
	<% if @cart.line_items.length.zero? %>
		<tr>
			<td>
				<p class="flow-text">
					Корзина пуста
				</p>
			</td>
		</tr>
	</table>

	<br><br>

	<div>
		<%= link_to 'В каталог', store_path, class: "btn btn-large cyan darken-1 waves-effect waves-light" %>
	</div>
	
	<% else %>
		<thead>
        	<tr>
        		<th></th>
            	<th data-field="title">Товарная позиция</th>
            	<th data-field="quantity">Количество</th>
            	<th data-field="price">Цена</th>
        	</tr>
        </thead>
		<%= render @cart.line_items %>
		<tr class="total_line">
			<td></td>
			<td></td>
			<td>Итог</td>
			<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
		</tr>
	</table>

	<br><br>

	<%= link_to 'Оформить заказ', new_order_path, class: "btn btn-large order-button waves-effect waves-light" %>
	<% end %>
</div>

<br><br><br><br>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$('#cart').html("<%= escape_javascript render(@cart) %>");
$('#cart-badge').html("<%= escape_javascript render partial: 'carts/badge', object: @cart %>");

app/views/carts/edit.html.erb
<h2 class="header">Редактирование корзины</h2>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="header">Список корзин</h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h2 class="header">Новая корзина</h2>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @cart %>