config/routes.rb
Rails.application.routes.draw do
  resources :slides

  resources :category_products

  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :who_bought, on: :member
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :image_attachments

  resources :line_item_attributes

  resources :product_attributes

  resources :orders
  resources :orders do
    member do
      post 'shipped'
    end
  end

  resources :line_items
  resources :carts
  get 'payment', to: 'store#payment', as: 'payment'
  get 'contacts', to: 'store#contacts', as: 'contacts'
  get 'about', to: 'store#about', as: 'about'
  get 'store/index'
  get 'store/search', to: 'store#search', as: 'store_search'
  get 'store/:id', to: 'store#show', as: 'store_show'
  resources :products

  root to: 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product, params)
		quantity = params[:quantity].to_i || 1

		current_item = line_items.where(product_id: product.id).map do |current|
			product_attributes = params.reject { |key, value| product.product_attributes.find_by(title: key, id: value).nil? }.map{|key, value| value.to_i}
			if current.line_item_attribute.pluck(:product_attribute_id).uniq.sort == product_attributes.uniq.sort
				current.quantity += quantity
				current
			else
				nil
			end
		end

		unless current_item.nil? || current_item.empty?
			current_item = current_item.compact.first
		end

		if current_item.nil? || current_item == []
			current_item = line_items.build(product_id: product.id, quantity: quantity)
			params.each do |key, value|
		      	attribute_attribute = product.product_attributes.find_by(title: key, id: value)
		      	unless attribute_attribute.nil?
		        	current_item.line_item_attribute.build(product_attribute_id: attribute_attribute.id)
		      	end
	    	end
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :category_products, dependent: :destroy
	has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/image_attachment.rb
class ImageAttachment < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  has_many :line_item_attribute

  def price
  	product.price + line_item_attribute.to_a.sum {|n| n.product_attribute.price.to_i}
  end

  def total_price
  	price * quantity
  end
end

app/models/line_item_attribute.rb
class LineItemAttribute < ActiveRecord::Base
  belongs_to :product_attribute
  belongs_to :line_item
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :email, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#	validates :status, inclusion: {in: valid_status}, presence: true
	has_many :line_items, dependent: :destroy

	STATUS = {
		ordered: 'Заказ размещен',
		changed: 'Были внесены изменения в заказ',
		shipped: 'Заказ отправлен',
		archived: 'В архиве'
	}

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
			self.status = STATUS[:ordered]
		end
	end

	def self.status
		STATUS
	end

	def change_status(new_status)
		self.status = STATUS[new_status]
	end

	def self.valid_status
		STATUS.keys
	end
end

app/models/product.rb
require 'babosa'

class Product < ActiveRecord::Base
	searchkick
	extend FriendlyId
	friendly_id :slug_candidates, use: [:slugged, :finders]
	validates :title, :price, presence: true
	has_many :line_items
	has_many :category_products
	has_many :categories, through: :category_products
	has_many :product_attributes
	has_many :image_attachments
	accepts_nested_attributes_for :image_attachments
	has_many :orders, through: :line_items
  	attr_accessor :quantity

	before_destroy :ensure_not_referenced_by_any_line_item

	def quantity
	  @quantity || 1
	end

	def quantity=(value)
	  @quantity = value
	end

	def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  	end

	def normalize_friendly_id(text)
		text.to_s.to_slug.normalize(transliterations: :russian).to_s
	end

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end
end

app/models/product_attribute.rb
class ProductAttribute < ActiveRecord::Base
  validates :title, :value, :product_id, presence: true
  belongs_to :product, dependent: :destroy
end

app/models/slide.rb
class Slide < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  validates :name, presence: true, uniqueness: true
  has_secure_password

  private
  	def ensure_an_admin_remains
  		if User.count.zero?
  			raise "Последний пользователь не может быть удален."
  		end
  	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  include CurrentCart, CategoriesAvailable
  before_action :set_cart, :categories

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <br>
  <br>
  
  <%= link_to 'Submit', '#', class: "btn btn-large red accent-2 waves-effect waves-light", onclick: "$('form').submit()" %>
  <%= f.submit nil, style: "display: none;" %>

  <br>
  <br>

<% end %>

app/views/categories/_index.html.erb
<li class="logo">
	<%= link_to store_path, id: "logo-container", class: "brand-logo"  do %>
		<object id="front-page-logo" class="object-brand" type="image/svg+xml" data="/assets/logo.svg">На главную</object>
    <% end %>
</li>
<% @categories && @categories.each do |category| %>
  <li>
    <%= link_to category.title, store_path(:category => category.id), class: "truncate waves-effect waves-light" %>
  </li>
<% end %>


<% if session[:user_id] %>
	<li class="dashboard">
		<%= link_to "Dashboard", admin_path, class: "truncate waves-effect waves-light" %>
	</li>
	<li class="dashboard">
		<%= link_to "Logout", logout_path, method: :delete, class: "truncate waves-effect waves-light" %>
	</li>
<% end %>

app/views/categories/edit.html.erb
<h2 class="header">Редактирование категории</h2>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2 class="header">Список категорий</h2>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h2 class="header">Новая категория</h2>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>