config/routes.rb
Rails.application.routes.draw do
  resources :slides

  resources :category_products

  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :products do
    get :who_bought, on: :member
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :image_attachments

  resources :line_item_attributes

  resources :product_attributes

  resources :orders
  resources :orders do
    member do
      post 'shipped'
    end
  end

  resources :line_items
  resources :carts
  get 'payment', to: 'store#payment', as: 'payment'
  get 'contacts', to: 'store#contacts', as: 'contacts'
  get 'about', to: 'store#about', as: 'about'
  get 'store/index'
  get 'store/search', to: 'store#search', as: 'store_search'
  get 'store/:id', to: 'store#show', as: 'store_show'
  resources :products

  root to: 'store#index', as: 'store'

end

app/models/product.rb
require 'babosa'

class Product < ActiveRecord::Base
	searchkick
	extend FriendlyId
	friendly_id :slug_candidates, use: [:slugged, :finders]
	validates :title, :price, presence: true
	has_many :line_items
	has_many :category_products
	has_many :categories, through: :category_products
	has_many :product_attributes
	has_many :image_attachments
	accepts_nested_attributes_for :image_attachments
	has_many :orders, through: :line_items
  	attr_accessor :quantity

	before_destroy :ensure_not_referenced_by_any_line_item

	def quantity
	  @quantity || 1
	end

	def quantity=(value)
	  @quantity = value
	end

	def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  	end

	def normalize_friendly_id(text)
		text.to_s.to_slug.normalize(transliterations: :russian).to_s
	end

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart, CategoriesAvailable
  before_action :set_cart, :categories
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @image_attachments = @product.image_attachments.all
  end

  # GET /products/new
  def new
    @product = Product.new
    @image_attachments = @product.image_attachments.build
  end

  # GET /products/1/edit
  def edit
    @image_attachments = (@product.image_attachments.all unless @product.image_attachments.all.length == 0) || @product.image_attachments.build
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        unless params[:image_attachments].nil?
          params[:image_attachments]['image'].each do |a|
            @image_attachments = @product.image_attachments.create!(:image => a)
          end
        end
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        @image_attachments = @product.image_attachments.build
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      unless params[:image_attachments].nil?
        params[:image_attachments]['image'].each do |a|
          @image_attachments = @product.image_attachments.create!(:image => a)
        end
      end
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :article, :description, :price, image_attachments_attributes: [:id, :product_id, :image])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h4 class="header">Проблемы возникли со следующими полями:</h4>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <%= f.fields_for :image_attachments do |p| %>
    <%= f.label :image %><br>
    <div class="field file-field input-field">
      <div class="btn">
        <span>File</span>
        <%= p.file_field :image, :multiple => true, name: "image_attachments[image][]" %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <br>
  <% end %>

  <br>
  <br>

  <%= link_to 'Submit', '#', class: "btn btn-large red accent-2 waves-effect waves-light", onclick: "$('form').submit()" %>
  <%= f.submit nil, style: "display: none;" %>
  
  <br>
  <br>
  
<% end %>

app/views/products/edit.html.erb
<h2 class="header">Редактирование продукта</h2>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="header">Список продуктов</h2>

<table class="bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'Новый продукт', new_product_path, class: "btn btn-large red accent-2 waves-effect waves-light" %>

<br>
<br>

app/views/products/new.html.erb
<h2 class="header">Новый продукт</h2>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Article:</strong>
  <%= @product.article %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<% @image_attachments.each do |p| %>
  <%= image_tag p.image_url %>
  <%= link_to "Edit Attachment", edit_image_attachment_path(p) %>
<% end %>
<br>
<br>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>